### ISSUE TITLE
The new train script train_distll.py seems optimze all parameters.

### ISSUE THREAD

**Issue by yynil** [jxiw/MambaInLlama#20]
In the previous version train_hybrid.py, I can see the script freeze all non-mamba module. But in the train_distill.py, I didn't find this setup. It means even MLPs are updated in the new process. I'm not sure if I understand the current distillation process correctly.

**Comment by jxiw** [comment]
Hi, thank you for this question. Our distillation has 3 steps.

1. Stepwise layer alignment (Optional). Replace the attention layers by Mamba2, one by one in a stepwise manner.
2. End to end distillation (Most important). Minimize KL divergence loss between the student and teacher models. You can consider to use a larger teacher model to get better results.
3. Instruction tuning (Optional). For simplicity, we use SFT + DPO for this process.

So in the step 1, if you want to align the model layer by layer, you need freeze the MLP layers.

However, in the 2 and 3 steps. All parameters are finetuned.

In our paper, we describe a combined loss KL + CE for the step 2. But the original model is trained in CE, while later we change it to KL loss in the new version since we obverse a better performance.

We omit the step 1 because we use a larger model in step 2 which takes more time to train (we want to restrict the training time a bit). 

But in my original experiments, we show that step 1 can improve MMLU to 2 - 3.

So if you have enough GPUs and not worry about the training time, i suggest you do step 1 + step 2 (KL loss with a larger model as teacher model)

If you don't have GPUs and only want to get a sense how does reuse KQVO projections (initialize KQVO weights) this idea works, i suggest you only do step 2 using KL loss with a larger teacher model.

**Comment by yynil** [comment]
Thanks for your kindly help and clear and thoughtful answer and sharing!
