### ISSUE TITLE
train_hybrid.py vs train_distill.py

### ISSUE THREAD

**Issue by xfxcwynlc** [jxiw/MambaInLlama#21]
Thank you for the excellent work provided in the [MambaInLlama README](https://github.com/jxiw/MambaInLlama/blob/main/mamba_llama/README.md). I have primarily been using train_hybrid.py during my experiments and have largely overlooked train_distill.py so far.

From the related discussions, it seems that train_distill.py optimizes all parameters, including the MLP layers, while train_hybrid.py focuses on training only the MambaDecoderLayers and keeps other components frozen. Specifically in ([Issue #20](https://github.com/jxiw/MambaInLlama/issues/20)), you mentioned that freezing layers happens at Step 1, while end-to-end distillation (Step 2), where all parameters are fine-tuned, is the most important step.

This raises a few questions:

1. Based on my understanding of the [MambaInLlama README](https://github.com/jxiw/MambaInLlama/blob/main/mamba_llama/README.md), train_hybrid.py already covers stepwise layer alignment and distillation. However, since train_hybrid.py does not update all parameters, do we still need to perform end-to-end distillation separately by running train_distill.py?

2. Considering the recommended training pipeline (stepwise layer training, end to end distillation, instruction tuning), how do train_hybrid.py and train_distill.py fit into the overall workflow?

My main goal is to distill Mamba Hybrid models using other Hugging Face transformers, and I would greatly appreciate clarification on the specific roles for train_hybrid.py and train_distill.py within the training pipeline.

Thanks in advance : )

**Comment by jxiw** [comment]
Question 1, yeah, no matter whether you perform stepwise layer alignment, you do need the perform end-to-end training (and that is step 2 here) and that is the most important. In the paper, we use GPT-4 synthetic data and trained with SFT to perform the end to end training. But maybe because of data quality or others, we actually find using larger model for example llama 3.1 70B to distill is better than doing SFT directly on GPT-4 synthetic data. So train_distill.py is to replace the train_sft.py.

Question 2, I should remove those files, there are a bit confused. train_hybrid.py should be train_layer_alignment.py and train_distill.py should be train_end_to_end_distill.py.

Thank you for your questions. If you have further concerns, please let me konw.

**Comment by jxiw** [comment]
Thank you for this questions. Since this is super confused, I also add this in the README.md!

**Comment by xfxcwynlc** [comment]
It's really clear :) thanks a lot!

**Comment by xfxcwynlc** [comment]
It's really clear :) thanks a lot!
