### ISSUE TITLE
State size vs hidden size, finding N'

### ISSUE THREAD

**Issue by Codys12** [jxiw/MambaInLlama#7]
Is there anywhere in the code, particularly around hybrid_decoder_layer, where the state size is made explicit? I am looking for `N'`, and am trying to derive it from hidden size and state size

**Comment by jxiw** [comment]
Hi, thanks for raising this great questions!

It depends on whether model is Mamba1 or Mamba2.

If you look at this figure. Mamba1 gets very slow for large state size. For the speed propose, we just set the state size to 16. So the number of head/group is 4096/16=256. But you can try to change this line if you want different state size, https://github.com/jxiw/MambaInLlama/blob/main/train_mamba/train_hybrid.py#L86. Just do something like {"expand": 1, "d_state":16}

<img width="645" alt="Screenshot 2024-09-11 at 12 33 07 PM" src="https://github.com/user-attachments/assets/15092c4b-d9f1-4ecb-8532-35d7ff6b7cb8">

For Mamba2, we use the same head/group as transformers, and use the same state size as hidden size per head as here,
https://github.com/jxiw/MambaInLlama/blob/main/train_mamba2/train_hybrid.py#L92

**Comment by Codys12** [comment]
Does this mean that compared to linear attention, the effective expansion (N’) would be 128 for Llama (hidden // nheads)? Or would it be something else like nheads?

**Comment by jxiw** [comment]
So, for Mamba2, I believe N' = 1, as we keep the same head and head dimension as the transformer. Therefore, we don't have any effective expansion. For Mamba1, it is more complicated since we don’t actually expand the state size but rather choose a smaller one, purely for performance reasons. The effective expansion (N’) described in our paper is more accurately aligned with the Mamba2 version. Again, thank you for raising these great questions.

**Comment by Codys12** [comment]
Thank you for the great answers!
